baseURL = "https://shiatsuki.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Shiatsuki | Marie Poidevin Praticienne"
[[menu.main]]
URL = "soins"
name = "Soins & Prestations"
weight = 3
[[menu.main]]
URL = "actu"
name = "Actualit√©s"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "125/A, CA Commercial Area, California, USA"
author = "Marie Poidevin"
copyright = "Copyright &copy; 2020 a site created by [Alan Pacaud](https://github.com/alanpacaud)"
description = "Praticienne en Shiatsu"
email = "marie.poidevin@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/logo-libellule-final.png"
phone = "+880 2544 658 256"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
