baseURL = "https://shiatsuki.netlify.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Mapishu"
[[menu.main]]
URL = "shiatsu"
name = "Shiatsu"
weight = 3
[[menu.main]]
URL = "soins"
name = "Autres Soins"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "42 rue de la gare, 44140 Monbert, France"
author = "Marie Poidevin"
copyright = "Copyright &copy; 2020 a site created by [Alan Pacaud](https://github.com/alanpacaud)"
description = "Praticienne en Shiatsu"
email = "marie.poidevin@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/logomapishu.png"
phone = "+880 2544 658 256"
theme_color = "#F2E6B6"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/mapishiatsu"
icon = "images/iconefinder_facebook.png"
[[params.social]]
URL = "#"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-instagram"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
